projectname    GumEssentials

srcdir         src
exampledir     examples

findlibraries  SELF GumMaths GumSystem
headerfiles    gum-essentials Essentials/
examples       Playground

extralibraries_begin
extralibraries_end

extraincludepaths_begin
extraincludepaths_end

customstr_begin
customstr_end
